# Generated by Django 5.2.13 on 2026-04-30 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('politica_privacidad', models.CharField(choices=[('ABIERTA', 'Historia Clínica Abierta (Todos ven todo)'), ('AREA', 'Privacidad por Área (Solo misma especialidad)'), ('ESTRICTA', 'Privacidad Estricta (Solo el médico autor)')], default='ABIERTA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad_nombre', models.CharField(editable=False, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('bloqueado', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='gestion.paciente')),
                ('turno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolucion', to='gestion.turno')),
            ],
            options={
                'verbose_name_plural': 'Evoluciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='historias_clinicas/%Y/%m/%d/')),
                ('descripcion_archivo', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('evolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestion.evolucion')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, help_text='Ej: Penicilina, látex, etc.')),
                ('enfermedades_cronicas', models.TextField(blank=True, help_text='Ej: Diabetes Tipo 2, Hipertensión.')),
                ('medicacion_habitual', models.TextField(blank=True, help_text='Lo que el paciente toma siempre.')),
                ('antecedentes_familiares', models.TextField(blank=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_clinico', to='gestion.paciente')),
                ('ultimo_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.medico')),
            ],
        ),
    ]
