# Generated by Django 5.2.13 on 2026-05-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_configuracionclinica_evolucion_evolucionarchivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AddField(
            model_name='evolucion',
            name='evolucion_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='gestion.evolucion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='es_particular',
            field=models.BooleanField(default=False),
        ),
    ]
